version: '3'

services:
    postgres:
        image: postgres:17-alpine
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        build: .
        ports:
            - "8000:8000"
            - 9000
        volumes:
            - ./:/app
        depends_on:
            - postgres
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    postgres_data:
