openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://localhost:8000/api

tags:
  - name: customers
    description: "[Customers] Rotas para o recurso de cliente"
  - name: products
    description: "[Products] Rotas para o recurso de produto"
  - name: orders
    description: "[Orders] Rotas para o recurso de pedido"

paths:
  /customers:
    $ref: 'customer/doc.yaml'
  /customers/orders:
    $ref: 'customer/order/create.yaml'

  /establishment/products:
    $ref: 'establishment/product.yaml'
  /establishment/products/{productuuid}:
    $ref: 'establishment/product/update.yaml'
  /establishment/categories/{categoryUuid}/products:
    $ref: 'establishment/product/all-by-category.yaml'
