apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv
  labels:
    name: pgsql-pv
spec:
  capacity:
    storage: 100Mi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/postgres/data"
