apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc
  labels:
    name: pgsql-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
