apiVersion: v1
kind: Service
metadata:
  name: postech-db-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postech-db-deployment
  ports:
    - port: 5432
      targetPort: 5432
